#!/bin/bash 

set -e 


# 获取数据源相关参数
DB_HOST=${DB_HOST:-}   # 当用外部数据库时需要, 如果没有, 则在linked mysql中查找
DB_PORT=${DB_PORT:-}   # 当用外部数据库时需要, 如果没有, 则在linked mysql中查找

# 一下是必须的!!!, 
DB_NAME=${DB_NAME:-}
DB_USER=${DB_USER:-}
DB_PASS=${DB_PASS:-}

# 存在环境变量MYSQL_PORT_3306_TCP_ADDR,　那么就是link了mysql数据库
if [ -n "${MYSQL_PORT_3306_TCP_ADDR}" ]; then
  DB_HOST=${DB_HOST:-${MYSQL_PORT_3306_TCP_ADDR}}
  DB_PORT=${DB_PORT:-${MYSQL_PORT_3306_TCP_PORT}}

  # support for linked sameersbn/mysql image
  DB_NAME=${DB_NAME:-${MYSQL_ENV_DB_NAME}}
  DB_USER=${DB_USER:-${MYSQL_ENV_DB_USER}}
  DB_PASS=${DB_PASS:-${MYSQL_ENV_DB_PASS}}
fi

if [ -z "$DB_HOST" ]; then
    echo "DB_HOST can not be determined";
    exit -1;
fi
if [ -z "$DB_PORT" ]; then
    echo "DB_PORT can not be determined";
    exit -2;
fi
if [ -z "$DB_NAME" ]; then
    echo "DB_NAME can not be determined";
    exit -3;
fi
if [ -z "$DB_USER" ]; then
    echo "DB_USER can not be determined";
    exit -4;
fi
if [ -z "$DB_PASS" ]; then
    echo "DB_PASS can not be determined";
    exit -5;
fi

# 配置数据源
sudo -u archiva -H sed 's/{{DB_HOST}}/'"${DB_HOST}"'/' -i  /home/archiva/opt/archiva/conf/jetty.xml
sudo -u archiva -H sed 's/{{DB_PORT}}/'"${DB_PORT}"'/' -i  /home/archiva/opt/archiva/conf/jetty.xml
sudo -u archiva -H sed 's/{{DB_NAME}}/'"${DB_NAME}"'/' -i  /home/archiva/opt/archiva/conf/jetty.xml
sudo -u archiva -H sed 's/{{DB_USER}}/'"${DB_USER}"'/' -i  /home/archiva/opt/archiva/conf/jetty.xml
sudo -u archiva -H sed 's/{{DB_PASS}}/'"${DB_PASS}"'/' -i  /home/archiva/opt/archiva/conf/jetty.xml

chown -R archiva:archiva /home/archiva/opt/archiva/logs;
chown -R archiva:archiva /home/archiva/opt/archiva/data;
chown -R archiva:archiva /home/archiva/opt/archiva/temp;

# 执行archiva!!!!!!
exec sudo -u archiva -H /home/archiva/run


